apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-secure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MateoDCRZ/gitops-demo-TP4.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: node-app-secure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
