apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-app-secure
spec:
  selector:
    app: node-app-secure
  ports:
    - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
